CREATE OR REPLACE PROCEDURE SP_LOAD_GOLD_STAGING()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Load Gold Daily Sales Staging
    INSERT INTO GOLD.DAILY_SALES_STG
    SELECT  
        TRANS_DT AS CAL_DT, 
        STORE_KEY, 
        PROD_KEY, 
        SUM(SALES_QTY) AS SALES_QTY, 
        SUM(SALES_AMT) AS SALES_AMT, 
        AVG(SALES_PRICE) AS SALES_PRICE, 
        SUM(SALES_COST) AS SALES_COST, 
        SUM(SALES_MGRN) AS SALES_MGRN, 
        AVG(DISCOUNT) AS DISCOUNT, 
        SUM(SHIP_COST) AS SHIP_COST, 
        CURRENT_TIMESTAMP() AS DW_CREATED_AT 
    FROM SILVER.SALES_FACT 
    WHERE TRANS_DT >= '1900-01-01' 
    GROUP BY 1, 2, 3;
    -- Load Gold Daily Inventory Staging
    INSERT INTO GOLD.DAILY_INVENTORY_STG
    SELECT 
        CAL_DT, 
        STORE_KEY, 
        PROD_KEY, 
        INVENTORY_ON_HAND_QTY AS STOCK_ON_HAND_QTY, 
        INVENTORY_ON_ORDER_QTY AS ORDERED_STOCK, 
        OUT_OF_STOCK_FLG, 
        WASTE_QTY, 
        PROMOTION_FLG, 
        NEXT_DELIVERY_DT, 
        CURRENT_TIMESTAMP() AS DW_CREATED_AT 
    FROM SILVER.INVENTORY_FACT 
    WHERE CAL_DT >= '1900-01-01';
    RETURN 'Gold Staging Loaded Successfully';
END;
$$;